language: php
php:
  - 5.4

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^v*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - printenv
  - composer self-update

install:
  - phpenv rehash
  - composer install

before_script:
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - ./bin/install_drupal_mysql.sh
  - cd html
  - drush runserver --server=builtin 8080 --strict=0 &
  - cd ..
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done

script:
  - ./bin/behat
